services:
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: timescaledb
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: bdspro
      #todo: the database creation doesnt seem to work yet, add manually for now
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
    networks:
      - ntw
  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    #  volumes:
    #     - ./db:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_USER=bdspro
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_DB=benchmark
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
    networks:
      - ntw

  benchmark_single:
    depends_on:
      - timescaledb
      - clickhouse
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src/main/java:/app
      - ./parameters.txt:/app/parameters.txt
      - ./results:/results
    networks:
      - ntw

  #benchmark_run:
  #  depends_on:
  #    - timescaledb
  #    - clickhouse
  #  build:
  #    context: ./
  #    dockerfile: Dockerfile
  #  volumes:
  #    - ./src/main/java:/app
  #  networks:
  #    - ntw

networks:
  ntw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.222.1.0/24