package com.bdspro.query;

public enum QueryType {
    EXACT_POINT,
    RANGE_ANY_ENTITY,
    RANGE_SINGLE_ENTITY,
    RANGE_WITH_VALUE_FILTER,
    RANGE_WITH_AGGREGATION_ON_TIME_COLUMN,
    LAST_N_RECORDS,
    RANGE_WITH_AGGREGATION,
    RANGE_WITH_AGGREGATION_WITHIN_GROUP,
    RANGE_WITH_AGGREGATION_AND_VALUE_FILTER,
    RANGE_WITH_LIMIT,
    RANGE_WITH_GROUP_BY_TIME,
    RANGE_WITH_ORDER_BY_VALUE,
    LATEST_POINT
}
